### ISSUE TITLE
Feature: Allow for custom dateEncodingStrategy when encoding JSON

### ISSUE THREAD

**Issue by Julianvantveld** [MountebankSwift/MountebankSwift#23]
When sending JsonEncodable objects to Mountebank, JsonEncoding is done using default strategy.
When an Encodable object uses a different date format compared to the default strategy JsonEncoding will fail.

For example a Date object with *.iso8601* encoding will now result into a timestamp (Int) due to the default *referenceDate* encoding. This causes issues with decoding since the data representation is no longer aligned with the value types in the en/decodable object.

Proposed fix: Allow for setting custom dateEncoding strategy.

```swift
private func encodeJson(encodable: Encodable) throws -> Data {
    do {
        jsonEncoder.dateEncodingStrategy = .iso8601
        return try jsonEncoder.encode(encodable)
    } catch {
        throw MountebankValidationError.invalidRequestData
    }
}
```

**Comment by teameh** [comment]
Thanks for the issue, I'll look into this. I think changing the `dateEncodingStrategy` here would affect all the other encoding as well. Perhaps we could allow this and other encode options along when you pass in the encodable you would like to encode: 

https://github.com/MountebankSwift/MountebankSwift/blob/main/Sources/MountebankSwift/Models/Stub/Response/Is/Is%2Binitializers.swift#L55

**Comment by teameh** [comment]
Fixed and merged in https://github.com/MountebankSwift/MountebankSwift/pull/24
